#!/usr/bin/env bash
# a Bash script that transfers a file
# from our client to a server

if [ $# != 4 ]
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

filePath="$1"
serverIp="$2"
username="$3"
sshKey="$4"

scp -o StrictHostKeyChecking=no -i $sshKey $filePath "$username@$serverIp":~/
