#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

redirect_me="\n\tlocation /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "/server_name _;/a \ $redirect_me" /etc/nginx/sites-available/default

#echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
#sudo sed -i "/^http {/a \ \n\terror_page 404 /404.html;" /etc/nginx/nginx.conf
sudo sed -i "/server_name _;/a \ \n\terror_page 404 /404.html;" /etc/nginx/sites-available/default

sudo sed -i '/try_files.*=404/s/^/#/' /etc/nginx/sites-available/default
E404_RULE="\tlocation /404.html {\n\
        \troot /var/www/html;\n\
	\tinternal;\n\
	}"
sudo sed -i "/error_page.*404.*;/a \ $E404_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
