#!/usr/bin/env bash

#sudo apt update
#sudo apt install -y nginx
#echo "Hello World!" | sudo tee /var/www/html/index.html

redirect_me="\n\tlocation /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "/server_name _;/a \ $redirect_me" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/^http {/a \ \n\terror_page 404 /404.html" /etc/nginx/nginx.conf

sudo service nginx restart
