#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update
sudo apt install -y haproxy

CONFIG="
backend web-backend
	balance roundrobin
	server 143015-web-01 54.157.184.77:80 check
	server 143015-web-02 18.234.130.161:80 check

frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
"

echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
