#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
#+receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"
echo "$$" > "$pid_file"

terminate () {
	echo "I hate the kill command"
	rm -f "$pid_file"
	exit 0
}

interrupt () {
	echo "Y U no love me?!"
}

quit () {
	rm -f "$pid_file"
	exit 0
}

trap terminate SIGTERM
trap interrupt SIGINT
trap quit SIGQUIT

while true; do
	echo "To infinity and beyond"
done
