#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
# displays bad luck from China for the 4th loop iteration
# displays bad luck from Japan for the 9th loop iteration
# displays bad luck from Italy for the other iterations

i=1
while ((i<21)); do
if ((i == 4)); then
	echo "bad luck from China"
elif ((i == 9)); then
	echo "bad luck from Japan"
elif ((i == 17)); then
	echo "bad luck from Italy"
else
	echo "$i"
fi
	((i++))
done
