#!/usr/bin/env bash
# Displays numbers from 1 to 20 and
# displays bad luck from China for the 4th loop iteration
# displays bad luck from Japan for the 9th loop iteration
# displays bad luck from Italy for the other iterations

i=1
while ((i<21)); do
case $i in
	5)
	echo "bad luck from China"
	echo "$i"
	;;
	10)
	echo "bad luck from Japan"
	echo "$i"
	;;
	18)
	echo "bad luck from Italy"
	echo "$i"
	;;
	*)
	echo "$i"
esac
	((i++))
done
