#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for ((i=0; i < 1; i++)); do
       touch t.txt
       ls > t.txt
       cut -d "-" -f 2 t.txt --only-delimited
       rm t.txt
done
