#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
  if [ -f "$file" ]; then
    name_after_dash="${file#*-}"
    if [ "$name_after_dash" != "$file" ]; then
      echo "$name_after_dash"
    fi
  fi
done
