#!/usr/bin/env bash
# configures ufw firewall

sudo ufw allow proto tcp in any from any port 22
sudo ufw allow proto tcp in any from any port 443
sudo ufw allow proto tcp in any from any port 80
sudo ufw enable
