#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on

# Use ip command to get the list of active interfaces and IPs
ip_info=$(ip -4 addr show)

echo "$ip_info" | awk '/inet / {print $2}' | cut -d'/' -f1
