#!/usr/bin/env bash
# configure a nginx user

sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default

sudo -u nginx service nginx restart
